name: Trigger Tests on Schedule and Manual

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter the tags to run (e.g., @smoke, @regression)'
        required: true
        default: '@smoke'
        type: string
  schedule:
    - cron: '30 18 * * 0'

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' 
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run Cucumber tests
        shell: pwsh
        run: |
          $TAGS = "${{ github.event.inputs.tags }}"
          
          Write-Host "DEBUG: Tags to be used for cucumber-js: '$TAGS'"

          if (-not $TAGS) {
            Write-Host "Running all tests"
            npm run cucumber
          } else {
            Write-Host "Running tests with tags: $TAGS"
            npx cucumber-js --tags "$TAGS"
          }

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cucumber-report
          path: reports/
          retention-days: 15
